// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeState():Promise<void>;

export function CurrentSong():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function Init(arg1:string):Promise<boolean>;

export function NextSong():Promise<void>;

export function OpenApp():Promise<boolean>;

export function PrevSong():Promise<void>;

export function Seek(arg1:number,arg2:string):Promise<void>;
