// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeState() {
  return window['go']['App']['App']['ChangeState']();
}

export function CurrentSong() {
  return window['go']['App']['App']['CurrentSong']();
}

export function Greet(arg1) {
  return window['go']['App']['App']['Greet'](arg1);
}

export function Init(arg1) {
  return window['go']['App']['App']['Init'](arg1);
}

export function NextSong() {
  return window['go']['App']['App']['NextSong']();
}

export function OpenApp() {
  return window['go']['App']['App']['OpenApp']();
}

export function PrevSong() {
  return window['go']['App']['App']['PrevSong']();
}

export function Seek(arg1, arg2) {
  return window['go']['App']['App']['Seek'](arg1, arg2);
}
