// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeState():Promise<void>;

export function CurrentSong():Promise<{[key: string]: string}>;

export function Greet(arg1:string):Promise<string>;

export function OpenApp():Promise<boolean>;
